# Generated by Django 3.1.14 on 2023-07-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0026_auto_20230616_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionnal',
            name='domaine',
        ),
        migrations.AddField(
            model_name='professionnal',
            name='domaine',
            field=models.ManyToManyField(to='formulaires.Person'),
        ),
    ]
