# Generated by Django 4.2.3 on 2023-07-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0028_alter_person_id_alter_professionnal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirit',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.person'),
        ),
    ]
