# Generated by Django 4.2.3 on 2023-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0029_alter_spirit_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionnal',
            name='working',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='diplomes',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='niveau',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='series',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='baptism_spirit',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='baptism_water',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='community',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='jeunesse',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
