# Generated by Django 4.2.3 on 2023-07-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0030_alter_person_commune_alter_person_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionnal',
            old_name='person',
            new_name='fk_professionnal',
        ),
        migrations.RenameField(
            model_name='scolaire',
            old_name='person',
            new_name='fk_scolaire',
        ),
        migrations.RenameField(
            model_name='spirit',
            old_name='person',
            new_name='fk_spirit',
        ),
    ]
