# Generated by Django 4.2.3 on 2023-07-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0031_rename_person_professionnal_fk_professionnal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionnal',
            name='domaine',
        ),
        migrations.AddField(
            model_name='professionnal',
            name='domaine',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
