# Generated by Django 4.2.3 on 2023-07-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0032_remove_professionnal_domaine_professionnal_domaine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionnal',
            old_name='fk_professionnal',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='scolaire',
            old_name='fk_scolaire',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='spirit',
            old_name='fk_spirit',
            new_name='person',
        ),
    ]
